/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.15.5 on Thu Jan 31 12:54:51 2019
 *
 * Copyright (c) 2014 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt.
 * 
 * This file may be used under the terms of the GNU General Public
 * License versions 2.0 or 3.0 as published by the Free Software
 * Foundation and appearing in the files LICENSE.GPL2 and LICENSE.GPL3
 * included in the packaging of this file.  Alternatively you may (at
 * your option) use any later version of the GNU General Public
 * License if such license has been publicly approved by Riverbank
 * Computing Limited (or its successors, if any) and the KDE Free Qt
 * Foundation. In addition, as a special exception, Riverbank gives you
 * certain additional rights. These rights are described in the Riverbank
 * GPL Exception version 1.1, which can be found in the file
 * GPL_EXCEPTION.txt in this package.
 * 
 * If you are unsure which license is appropriate for your use, please
 * contact the sales department at sales@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtSql.h"

#line 35 "/home/cct/LabRAD/PyQt-x11-gpl-4.10.4/sip/QtSql/qsql.sip"
#include <qsql.h>
#line 34 "/home/cct/LabRAD/PyQt-x11-gpl-4.10.4/QtSql/sipQtSqlQSql.cpp"


static sipEnumMemberDef enummembers_QSql[] = {
    {sipName_AfterLastRow, QSql::AfterLastRow, 1},
    {sipName_AllTables, QSql::AllTables, 5},
    {sipName_BeforeFirstRow, QSql::BeforeFirstRow, 1},
    {sipName_Binary, QSql::Binary, 4},
    {sipName_HighPrecision, QSql::HighPrecision, 2},
    {sipName_In, QSql::In, 4},
    {sipName_InOut, QSql::InOut, 4},
    {sipName_LowPrecisionDouble, QSql::LowPrecisionDouble, 2},
    {sipName_LowPrecisionInt32, QSql::LowPrecisionInt32, 2},
    {sipName_LowPrecisionInt64, QSql::LowPrecisionInt64, 2},
    {sipName_Out, QSql::Out, 4},
    {sipName_SystemTables, QSql::SystemTables, 5},
    {sipName_Tables, QSql::Tables, 5},
    {sipName_Views, QSql::Views, 5},
};


pyqt4ClassTypeDef sipTypeDef_QtSql_QSql = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_NAMESPACE,
        sipNameNr_QSql,
        {0}
    },
    {
        sipNameNr_QSql,
        {0, 0, 1},
        0, 0,
        14, enummembers_QSql,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    0,
    -1,
    -1,
    0,
    0,
    0,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0
},
    0,
    0,
    0
};
