/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.15.5 on Thu Jan 31 12:54:30 2019
 *
 * Copyright (c) 2014 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt.
 * 
 * This file may be used under the terms of the GNU General Public
 * License versions 2.0 or 3.0 as published by the Free Software
 * Foundation and appearing in the files LICENSE.GPL2 and LICENSE.GPL3
 * included in the packaging of this file.  Alternatively you may (at
 * your option) use any later version of the GNU General Public
 * License if such license has been publicly approved by Riverbank
 * Computing Limited (or its successors, if any) and the KDE Free Qt
 * Foundation. In addition, as a special exception, Riverbank gives you
 * certain additional rights. These rights are described in the Riverbank
 * GPL Exception version 1.1, which can be found in the file
 * GPL_EXCEPTION.txt in this package.
 * 
 * If you are unsure which license is appropriate for your use, please
 * contact the sales department at sales@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtCore.h"

#line 35 "/home/cct/LabRAD/PyQt-x11-gpl-4.10.4/sip/QtCore/qmetatype.sip"
#include <qmetatype.h>
#line 34 "/home/cct/LabRAD/PyQt-x11-gpl-4.10.4/QtCore/sipQtCoreQMetaType.cpp"



PyDoc_STRVAR(doc_QMetaType_type, "QMetaType.type(str) -> int");

extern "C" {static PyObject *meth_QMetaType_type(PyObject *, PyObject *);}
static PyObject *meth_QMetaType_type(PyObject *, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const char * a0;

        if (sipParseArgs(&sipParseErr, sipArgs, "s", &a0))
        {
            int sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = QMetaType::type(a0);
            Py_END_ALLOW_THREADS

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMetaType, sipName_type, doc_QMetaType_type);

    return NULL;
}


PyDoc_STRVAR(doc_QMetaType_typeName, "QMetaType.typeName(int) -> str");

extern "C" {static PyObject *meth_QMetaType_typeName(PyObject *, PyObject *);}
static PyObject *meth_QMetaType_typeName(PyObject *, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;

        if (sipParseArgs(&sipParseErr, sipArgs, "i", &a0))
        {
            const char *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = QMetaType::typeName(a0);
            Py_END_ALLOW_THREADS

            if (sipRes == NULL)
            {
                Py_INCREF(Py_None);
                return Py_None;
            }

            return SIPBytes_FromString(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMetaType, sipName_typeName, doc_QMetaType_typeName);

    return NULL;
}


PyDoc_STRVAR(doc_QMetaType_isRegistered, "QMetaType.isRegistered(int) -> bool");

extern "C" {static PyObject *meth_QMetaType_isRegistered(PyObject *, PyObject *);}
static PyObject *meth_QMetaType_isRegistered(PyObject *, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;

        if (sipParseArgs(&sipParseErr, sipArgs, "i", &a0))
        {
            bool sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = QMetaType::isRegistered(a0);
            Py_END_ALLOW_THREADS

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QMetaType, sipName_isRegistered, doc_QMetaType_isRegistered);

    return NULL;
}


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_QMetaType(void *, const sipTypeDef *);}
static void *cast_QMetaType(void *ptr, const sipTypeDef *targetType)
{
    if (targetType == sipType_QMetaType)
        return ptr;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_QMetaType(void *, int);}
static void release_QMetaType(void *sipCppV,int)
{
    Py_BEGIN_ALLOW_THREADS

    delete reinterpret_cast<QMetaType *>(sipCppV);

    Py_END_ALLOW_THREADS
}


extern "C" {static void assign_QMetaType(void *, SIP_SSIZE_T, const void *);}
static void assign_QMetaType(void *sipDst, SIP_SSIZE_T sipDstIdx, const void *sipSrc)
{
    reinterpret_cast<QMetaType *>(sipDst)[sipDstIdx] = *reinterpret_cast<const QMetaType *>(sipSrc);
}


extern "C" {static void *array_QMetaType(SIP_SSIZE_T);}
static void *array_QMetaType(SIP_SSIZE_T sipNrElem)
{
    return new QMetaType[sipNrElem];
}


extern "C" {static void *copy_QMetaType(const void *, SIP_SSIZE_T);}
static void *copy_QMetaType(const void *sipSrc, SIP_SSIZE_T sipSrcIdx)
{
    return new QMetaType(reinterpret_cast<const QMetaType *>(sipSrc)[sipSrcIdx]);
}


extern "C" {static void dealloc_QMetaType(sipSimpleWrapper *);}
static void dealloc_QMetaType(sipSimpleWrapper *sipSelf)
{
    if (sipIsPyOwned(sipSelf))
    {
        release_QMetaType(sipGetAddress(sipSelf),0);
    }
}


extern "C" {static void *init_type_QMetaType(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_type_QMetaType(sipSimpleWrapper *, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **, PyObject **sipParseErr)
{
    QMetaType *sipCpp = 0;

    {
        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, ""))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new QMetaType();
            Py_END_ALLOW_THREADS

            return sipCpp;
        }
    }

    {
        const QMetaType * a0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "J9", sipType_QMetaType, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new QMetaType(*a0);
            Py_END_ALLOW_THREADS

            return sipCpp;
        }
    }

    return NULL;
}


static PyMethodDef methods_QMetaType[] = {
    {SIP_MLNAME_CAST(sipName_isRegistered), meth_QMetaType_isRegistered, METH_VARARGS, SIP_MLDOC_CAST(doc_QMetaType_isRegistered)},
    {SIP_MLNAME_CAST(sipName_type), meth_QMetaType_type, METH_VARARGS, SIP_MLDOC_CAST(doc_QMetaType_type)},
    {SIP_MLNAME_CAST(sipName_typeName), meth_QMetaType_typeName, METH_VARARGS, SIP_MLDOC_CAST(doc_QMetaType_typeName)}
};

static sipEnumMemberDef enummembers_QMetaType[] = {
    {sipName_Bool, QMetaType::Bool, 135},
    {sipName_Char, QMetaType::Char, 135},
    {sipName_Double, QMetaType::Double, 135},
    {sipName_FirstGuiType, QMetaType::FirstGuiType, 135},
    {sipName_Float, QMetaType::Float, 135},
    {sipName_Int, QMetaType::Int, 135},
    {sipName_LastCoreType, QMetaType::LastCoreType, 135},
    {sipName_Long, QMetaType::Long, 135},
    {sipName_LongLong, QMetaType::LongLong, 135},
    {sipName_QBitArray, QMetaType::QBitArray, 135},
    {sipName_QBitmap, QMetaType::QBitmap, 135},
    {sipName_QBrush, QMetaType::QBrush, 135},
    {sipName_QByteArray, QMetaType::QByteArray, 135},
    {sipName_QChar, QMetaType::QChar, 135},
    {sipName_QColor, QMetaType::QColor, 135},
    {sipName_QCursor, QMetaType::QCursor, 135},
    {sipName_QDate, QMetaType::QDate, 135},
    {sipName_QDateTime, QMetaType::QDateTime, 135},
    {sipName_QEasingCurve, QMetaType::QEasingCurve, 135},
    {sipName_QFont, QMetaType::QFont, 135},
    {sipName_QIcon, QMetaType::QIcon, 135},
    {sipName_QImage, QMetaType::QImage, 135},
    {sipName_QKeySequence, QMetaType::QKeySequence, 135},
    {sipName_QLine, QMetaType::QLine, 135},
    {sipName_QLineF, QMetaType::QLineF, 135},
    {sipName_QLocale, QMetaType::QLocale, 135},
    {sipName_QMatrix, QMetaType::QMatrix, 135},
    {sipName_QMatrix4x4, QMetaType::QMatrix4x4, 135},
    {sipName_QObjectStar, QMetaType::QObjectStar, 135},
    {sipName_QPalette, QMetaType::QPalette, 135},
    {sipName_QPen, QMetaType::QPen, 135},
    {sipName_QPixmap, QMetaType::QPixmap, 135},
    {sipName_QPoint, QMetaType::QPoint, 135},
    {sipName_QPointF, QMetaType::QPointF, 135},
    {sipName_QPolygon, QMetaType::QPolygon, 135},
    {sipName_QQuaternion, QMetaType::QQuaternion, 135},
    {sipName_QRect, QMetaType::QRect, 135},
    {sipName_QRectF, QMetaType::QRectF, 135},
    {sipName_QRegExp, QMetaType::QRegExp, 135},
    {sipName_QRegion, QMetaType::QRegion, 135},
    {sipName_QSize, QMetaType::QSize, 135},
    {sipName_QSizeF, QMetaType::QSizeF, 135},
    {sipName_QSizePolicy, QMetaType::QSizePolicy, 135},
    {sipName_QString, QMetaType::QString, 135},
    {sipName_QStringList, QMetaType::QStringList, 135},
    {sipName_QTextFormat, QMetaType::QTextFormat, 135},
    {sipName_QTextLength, QMetaType::QTextLength, 135},
    {sipName_QTime, QMetaType::QTime, 135},
    {sipName_QTransform, QMetaType::QTransform, 135},
    {sipName_QUrl, QMetaType::QUrl, 135},
    {sipName_QVariant, QMetaType::QVariant, 135},
    {sipName_QVariantHash, QMetaType::QVariantHash, 135},
    {sipName_QVariantList, QMetaType::QVariantList, 135},
    {sipName_QVariantMap, QMetaType::QVariantMap, 135},
    {sipName_QVector2D, QMetaType::QVector2D, 135},
    {sipName_QVector3D, QMetaType::QVector3D, 135},
    {sipName_QVector4D, QMetaType::QVector4D, 135},
    {sipName_QWidgetStar, QMetaType::QWidgetStar, 135},
    {sipName_Short, QMetaType::Short, 135},
    {sipName_UChar, QMetaType::UChar, 135},
    {sipName_UInt, QMetaType::UInt, 135},
    {sipName_ULong, QMetaType::ULong, 135},
    {sipName_ULongLong, QMetaType::ULongLong, 135},
    {sipName_UShort, QMetaType::UShort, 135},
    {sipName_User, QMetaType::User, 135},
    {sipName_Void, QMetaType::Void, 135},
    {sipName_VoidStar, QMetaType::VoidStar, 135},
};

PyDoc_STRVAR(doc_QMetaType, "\1QMetaType()\n"
    "QMetaType(QMetaType)");


pyqt4ClassTypeDef sipTypeDef_QtCore_QMetaType = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_CLASS,
        sipNameNr_QMetaType,
        {0}
    },
    {
        sipNameNr_QMetaType,
        {0, 0, 1},
        3, methods_QMetaType,
        67, enummembers_QMetaType,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    doc_QMetaType,
    sipNameNr_PyQt4_QtCore_pyqtWrapperType,
    sipNameNr_sip_simplewrapper,
    0,
    0,
    init_type_QMetaType,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QMetaType,
    assign_QMetaType,
    array_QMetaType,
    copy_QMetaType,
    release_QMetaType,
    cast_QMetaType,
    0,
    0,
    0,
    0,
    0,
    0
},
    0,
    0,
    0
};
