/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.15.5 on Thu Jan 31 12:54:30 2019
 *
 * Copyright (c) 2014 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt.
 * 
 * This file may be used under the terms of the GNU General Public
 * License versions 2.0 or 3.0 as published by the Free Software
 * Foundation and appearing in the files LICENSE.GPL2 and LICENSE.GPL3
 * included in the packaging of this file.  Alternatively you may (at
 * your option) use any later version of the GNU General Public
 * License if such license has been publicly approved by Riverbank
 * Computing Limited (or its successors, if any) and the KDE Free Qt
 * Foundation. In addition, as a special exception, Riverbank gives you
 * certain additional rights. These rights are described in the Riverbank
 * GPL Exception version 1.1, which can be found in the file
 * GPL_EXCEPTION.txt in this package.
 * 
 * If you are unsure which license is appropriate for your use, please
 * contact the sales department at sales@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtCore.h"

#line 274 "/home/cct/LabRAD/PyQt-x11-gpl-4.10.4/sip/QtCore/qvariant.sip"
#include <qvariant.h>
#line 34 "/home/cct/LabRAD/PyQt-x11-gpl-4.10.4/QtCore/sipQtCoreQVariant_5.cpp"



extern "C" {static void assign_QVariant_5(void *, SIP_SSIZE_T, const void *);}
static void assign_QVariant_5(void *sipDst, SIP_SSIZE_T sipDstIdx, const void *sipSrc)
{
    reinterpret_cast<QVariant *>(sipDst)[sipDstIdx] = *reinterpret_cast<const QVariant *>(sipSrc);
}


extern "C" {static void *array_QVariant_5(SIP_SSIZE_T);}
static void *array_QVariant_5(SIP_SSIZE_T sipNrElem)
{
    return new QVariant[sipNrElem];
}


extern "C" {static void *copy_QVariant_5(const void *, SIP_SSIZE_T);}
static void *copy_QVariant_5(const void *sipSrc, SIP_SSIZE_T sipSrcIdx)
{
    return new QVariant(reinterpret_cast<const QVariant *>(sipSrc)[sipSrcIdx]);
}


/* Call the mapped type's destructor. */
extern "C" {static void release_QVariant_5(void *, int);}
static void release_QVariant_5(void *ptr, int)
{
    Py_BEGIN_ALLOW_THREADS
    delete reinterpret_cast<QVariant *>(ptr);
    Py_END_ALLOW_THREADS
}



extern "C" {static int convertTo_QVariant_5(PyObject *, void **, int *, PyObject *);}
static int convertTo_QVariant_5(PyObject *sipPy,void **sipCppPtrV,int *sipIsErr,PyObject *sipTransferObj)
{
    QVariant **sipCppPtr = reinterpret_cast<QVariant **>(sipCppPtrV);

#line 278 "/home/cct/LabRAD/PyQt-x11-gpl-4.10.4/sip/QtCore/qvariant.sip"
    if (!sipIsErr)
        // We can always convert to a QVariant.
        return 1;

    // If it is a null QVariant then just return it.
    if (Py_TYPE(sipPy) == sipTypeAsPyTypeObject(sipType_QPyNullVariant))
    {
        *sipCppPtr = reinterpret_cast<QVariant *>(
                sipConvertToType(sipPy, sipType_QPyNullVariant, sipTransferObj,
                        SIP_NO_CONVERTORS, 0, sipIsErr));

        return 0;
    }

    QVariant var = qpycore_PyObject_AsQVariant(sipPy, sipIsErr);

    if (*sipIsErr)
        return 0;

    *sipCppPtr = new QVariant(var);

    return sipGetState(sipTransferObj);
#line 98 "/home/cct/LabRAD/PyQt-x11-gpl-4.10.4/QtCore/sipQtCoreQVariant_5.cpp"
}


extern "C" {static PyObject *convertFrom_QVariant_5(void *, PyObject *);}
static PyObject *convertFrom_QVariant_5(void *sipCppV, PyObject *)
{
   QVariant *sipCpp = reinterpret_cast<QVariant *>(sipCppV);

#line 303 "/home/cct/LabRAD/PyQt-x11-gpl-4.10.4/sip/QtCore/qvariant.sip"
    return qpycore_PyObject_FromQVariant(*sipCpp);
#line 109 "/home/cct/LabRAD/PyQt-x11-gpl-4.10.4/QtCore/sipQtCoreQVariant_5.cpp"
}


extern "C" {static PyObject *meth_QVariant_5_nameToType(PyObject *, PyObject *);}
static PyObject *meth_QVariant_5_nameToType(PyObject *, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const char * a0;

        if (sipParseArgs(&sipParseErr, sipArgs, "s", &a0))
        {
            QVariant::Type sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = QVariant::nameToType(a0);
            Py_END_ALLOW_THREADS

            return sipConvertFromEnum(sipRes,sipType_QVariant_Type);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoFunction(sipParseErr, sipName_nameToType, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_QVariant_5_typeToName(PyObject *, PyObject *);}
static PyObject *meth_QVariant_5_typeToName(PyObject *, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QVariant::Type a0;

        if (sipParseArgs(&sipParseErr, sipArgs, "E", sipType_QVariant_Type, &a0))
        {
            const char *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = QVariant::typeToName(a0);
            Py_END_ALLOW_THREADS

            if (sipRes == NULL)
            {
                Py_INCREF(Py_None);
                return Py_None;
            }

            return SIPBytes_FromString(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoFunction(sipParseErr, sipName_typeToName, NULL);

    return NULL;
}


static PyMethodDef methods_QVariant_5[] = {
    {SIP_MLNAME_CAST(sipName_nameToType), meth_QVariant_5_nameToType, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_typeToName), meth_QVariant_5_typeToName, METH_VARARGS, NULL}
};

static sipEnumMemberDef enummembers_QVariant_5[] = {
    {sipName_BitArray, QVariant::BitArray, 250},
    {sipName_Bitmap, QVariant::Bitmap, 250},
    {sipName_Bool, QVariant::Bool, 250},
    {sipName_Brush, QVariant::Brush, 250},
    {sipName_ByteArray, QVariant::ByteArray, 250},
    {sipName_Char, QVariant::Char, 250},
    {sipName_Color, QVariant::Color, 250},
    {sipName_Cursor, QVariant::Cursor, 250},
    {sipName_Date, QVariant::Date, 250},
    {sipName_DateTime, QVariant::DateTime, 250},
    {sipName_Double, QVariant::Double, 250},
    {sipName_EasingCurve, QVariant::EasingCurve, 250},
    {sipName_Font, QVariant::Font, 250},
    {sipName_Hash, QVariant::Hash, 250},
    {sipName_Icon, QVariant::Icon, 250},
    {sipName_Image, QVariant::Image, 250},
    {sipName_Int, QVariant::Int, 250},
    {sipName_Invalid, QVariant::Invalid, 250},
    {sipName_KeySequence, QVariant::KeySequence, 250},
    {sipName_Line, QVariant::Line, 250},
    {sipName_LineF, QVariant::LineF, 250},
    {sipName_List, QVariant::List, 250},
    {sipName_Locale, QVariant::Locale, 250},
    {sipName_LongLong, QVariant::LongLong, 250},
    {sipName_Map, QVariant::Map, 250},
    {sipName_Matrix, QVariant::Matrix, 250},
    {sipName_Matrix4x4, QVariant::Matrix4x4, 250},
    {sipName_Palette, QVariant::Palette, 250},
    {sipName_Pen, QVariant::Pen, 250},
    {sipName_Pixmap, QVariant::Pixmap, 250},
    {sipName_Point, QVariant::Point, 250},
    {sipName_PointF, QVariant::PointF, 250},
    {sipName_Polygon, QVariant::Polygon, 250},
    {sipName_Quaternion, QVariant::Quaternion, 250},
    {sipName_Rect, QVariant::Rect, 250},
    {sipName_RectF, QVariant::RectF, 250},
    {sipName_RegExp, QVariant::RegExp, 250},
    {sipName_Region, QVariant::Region, 250},
    {sipName_Size, QVariant::Size, 250},
    {sipName_SizeF, QVariant::SizeF, 250},
    {sipName_SizePolicy, QVariant::SizePolicy, 250},
    {sipName_String, QVariant::String, 250},
    {sipName_StringList, QVariant::StringList, 250},
    {sipName_TextFormat, QVariant::TextFormat, 250},
    {sipName_TextLength, QVariant::TextLength, 250},
    {sipName_Time, QVariant::Time, 250},
    {sipName_Transform, QVariant::Transform, 250},
    {sipName_UInt, QVariant::UInt, 250},
    {sipName_ULongLong, QVariant::ULongLong, 250},
    {sipName_Url, QVariant::Url, 250},
    {sipName_UserType, QVariant::UserType, 250},
    {sipName_Vector2D, QVariant::Vector2D, 250},
    {sipName_Vector3D, QVariant::Vector3D, 250},
    {sipName_Vector4D, QVariant::Vector4D, 250},
};


sipMappedTypeDef sipTypeDef_QtCore_QVariant_5 = {
    {
        5,
        0,
        0,
        SIP_TYPE_ALLOW_NONE|SIP_TYPE_MAPPED,
        sipNameNr_QVariant,
        {0}
    },
    {
        sipNameNr_QVariant,
        {0, 0, 1},
        2, methods_QVariant_5,
        54, enummembers_QVariant_5,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
    },
    assign_QVariant_5,
    array_QVariant_5,
    copy_QVariant_5,
    release_QVariant_5,
    convertTo_QVariant_5,
    convertFrom_QVariant_5
};
