/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.15.5 on Thu Jan 31 12:54:41 2019
 *
 * Copyright (c) 2014 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt.
 * 
 * This file may be used under the terms of the GNU General Public
 * License versions 2.0 or 3.0 as published by the Free Software
 * Foundation and appearing in the files LICENSE.GPL2 and LICENSE.GPL3
 * included in the packaging of this file.  Alternatively you may (at
 * your option) use any later version of the GNU General Public
 * License if such license has been publicly approved by Riverbank
 * Computing Limited (or its successors, if any) and the KDE Free Qt
 * Foundation. In addition, as a special exception, Riverbank gives you
 * certain additional rights. These rights are described in the Riverbank
 * GPL Exception version 1.1, which can be found in the file
 * GPL_EXCEPTION.txt in this package.
 * 
 * If you are unsure which license is appropriate for your use, please
 * contact the sales department at sales@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtNetwork.h"

#line 34 "/home/cct/LabRAD/PyQt-x11-gpl-4.10.4/sip/QtNetwork/qsslerror.sip"
#include <qsslerror.h>
#line 34 "/home/cct/LabRAD/PyQt-x11-gpl-4.10.4/QtNetwork/sipQtNetworkQSslError.cpp"

#line 34 "/home/cct/LabRAD/PyQt-x11-gpl-4.10.4/sip/QtNetwork/qsslcertificate.sip"
#include <qsslcertificate.h>
#line 38 "/home/cct/LabRAD/PyQt-x11-gpl-4.10.4/QtNetwork/sipQtNetworkQSslError.cpp"
#line 36 "/home/cct/LabRAD/PyQt-x11-gpl-4.10.4/sip/QtCore/qstring.sip"
#include <qstring.h>
#line 41 "/home/cct/LabRAD/PyQt-x11-gpl-4.10.4/QtNetwork/sipQtNetworkQSslError.cpp"


PyDoc_STRVAR(doc_QSslError_error, "QSslError.error() -> QSslError.SslError");

extern "C" {static PyObject *meth_QSslError_error(PyObject *, PyObject *);}
static PyObject *meth_QSslError_error(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QSslError *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QSslError, &sipCpp))
        {
            QSslError::SslError sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->error();
            Py_END_ALLOW_THREADS

            return sipConvertFromEnum(sipRes,sipType_QSslError_SslError);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QSslError, sipName_error, doc_QSslError_error);

    return NULL;
}


PyDoc_STRVAR(doc_QSslError_errorString, "QSslError.errorString() -> QString");

extern "C" {static PyObject *meth_QSslError_errorString(PyObject *, PyObject *);}
static PyObject *meth_QSslError_errorString(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QSslError *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QSslError, &sipCpp))
        {
            QString *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QString(sipCpp->errorString());
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QSslError, sipName_errorString, doc_QSslError_errorString);

    return NULL;
}


PyDoc_STRVAR(doc_QSslError_certificate, "QSslError.certificate() -> QSslCertificate");

extern "C" {static PyObject *meth_QSslError_certificate(PyObject *, PyObject *);}
static PyObject *meth_QSslError_certificate(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QSslError *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QSslError, &sipCpp))
        {
            QSslCertificate *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QSslCertificate(sipCpp->certificate());
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QSslCertificate,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QSslError, sipName_certificate, doc_QSslError_certificate);

    return NULL;
}


extern "C" {static PyObject *slot_QSslError___ne__(PyObject *,PyObject *);}
static PyObject *slot_QSslError___ne__(PyObject *sipSelf,PyObject *sipArg)
{
    QSslError *sipCpp = reinterpret_cast<QSslError *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QSslError));

    if (!sipCpp)
        return 0;

    PyObject *sipParseErr = NULL;

    {
        const QSslError * a0;

        if (sipParseArgs(&sipParseErr, sipArg, "1J9", sipType_QSslError, &a0))
        {
            bool sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->QSslError::operator!=(*a0);
            Py_END_ALLOW_THREADS

            return PyBool_FromLong(sipRes);
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    return sipPySlotExtend(&sipModuleAPI_QtNetwork,ne_slot,sipType_QSslError,sipSelf,sipArg);
}


extern "C" {static PyObject *slot_QSslError___eq__(PyObject *,PyObject *);}
static PyObject *slot_QSslError___eq__(PyObject *sipSelf,PyObject *sipArg)
{
    QSslError *sipCpp = reinterpret_cast<QSslError *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QSslError));

    if (!sipCpp)
        return 0;

    PyObject *sipParseErr = NULL;

    {
        const QSslError * a0;

        if (sipParseArgs(&sipParseErr, sipArg, "1J9", sipType_QSslError, &a0))
        {
            bool sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->QSslError::operator==(*a0);
            Py_END_ALLOW_THREADS

            return PyBool_FromLong(sipRes);
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    return sipPySlotExtend(&sipModuleAPI_QtNetwork,eq_slot,sipType_QSslError,sipSelf,sipArg);
}


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_QSslError(void *, const sipTypeDef *);}
static void *cast_QSslError(void *ptr, const sipTypeDef *targetType)
{
    if (targetType == sipType_QSslError)
        return ptr;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_QSslError(void *, int);}
static void release_QSslError(void *sipCppV,int)
{
    Py_BEGIN_ALLOW_THREADS

    delete reinterpret_cast<QSslError *>(sipCppV);

    Py_END_ALLOW_THREADS
}


extern "C" {static void assign_QSslError(void *, SIP_SSIZE_T, const void *);}
static void assign_QSslError(void *sipDst, SIP_SSIZE_T sipDstIdx, const void *sipSrc)
{
    reinterpret_cast<QSslError *>(sipDst)[sipDstIdx] = *reinterpret_cast<const QSslError *>(sipSrc);
}


extern "C" {static void *array_QSslError(SIP_SSIZE_T);}
static void *array_QSslError(SIP_SSIZE_T sipNrElem)
{
    return new QSslError[sipNrElem];
}


extern "C" {static void *copy_QSslError(const void *, SIP_SSIZE_T);}
static void *copy_QSslError(const void *sipSrc, SIP_SSIZE_T sipSrcIdx)
{
    return new QSslError(reinterpret_cast<const QSslError *>(sipSrc)[sipSrcIdx]);
}


extern "C" {static void dealloc_QSslError(sipSimpleWrapper *);}
static void dealloc_QSslError(sipSimpleWrapper *sipSelf)
{
    if (sipIsPyOwned(sipSelf))
    {
        release_QSslError(sipGetAddress(sipSelf),0);
    }
}


extern "C" {static void *init_type_QSslError(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_type_QSslError(sipSimpleWrapper *, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **, PyObject **sipParseErr)
{
    QSslError *sipCpp = 0;

    {
        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, ""))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new QSslError();
            Py_END_ALLOW_THREADS

            return sipCpp;
        }
    }

    {
        QSslError::SslError a0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "E", sipType_QSslError_SslError, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new QSslError(a0);
            Py_END_ALLOW_THREADS

            return sipCpp;
        }
    }

    {
        QSslError::SslError a0;
        const QSslCertificate * a1;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "EJ9", sipType_QSslError_SslError, &a0, sipType_QSslCertificate, &a1))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new QSslError(a0,*a1);
            Py_END_ALLOW_THREADS

            return sipCpp;
        }
    }

    {
        const QSslError * a0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "J9", sipType_QSslError, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new QSslError(*a0);
            Py_END_ALLOW_THREADS

            return sipCpp;
        }
    }

    return NULL;
}


/* Define this type's Python slots. */
static sipPySlotDef slots_QSslError[] = {
    {(void *)slot_QSslError___ne__, ne_slot},
    {(void *)slot_QSslError___eq__, eq_slot},
    {0, (sipPySlotType)0}
};


static PyMethodDef methods_QSslError[] = {
    {SIP_MLNAME_CAST(sipName_certificate), meth_QSslError_certificate, METH_VARARGS, SIP_MLDOC_CAST(doc_QSslError_certificate)},
    {SIP_MLNAME_CAST(sipName_error), meth_QSslError_error, METH_VARARGS, SIP_MLDOC_CAST(doc_QSslError_error)},
    {SIP_MLNAME_CAST(sipName_errorString), meth_QSslError_errorString, METH_VARARGS, SIP_MLDOC_CAST(doc_QSslError_errorString)}
};

static sipEnumMemberDef enummembers_QSslError[] = {
    {sipName_AuthorityIssuerSerialNumberMismatch, QSslError::AuthorityIssuerSerialNumberMismatch, 96},
    {sipName_CertificateBlacklisted, QSslError::CertificateBlacklisted, 96},
    {sipName_CertificateExpired, QSslError::CertificateExpired, 96},
    {sipName_CertificateNotYetValid, QSslError::CertificateNotYetValid, 96},
    {sipName_CertificateRejected, QSslError::CertificateRejected, 96},
    {sipName_CertificateRevoked, QSslError::CertificateRevoked, 96},
    {sipName_CertificateSignatureFailed, QSslError::CertificateSignatureFailed, 96},
    {sipName_CertificateUntrusted, QSslError::CertificateUntrusted, 96},
    {sipName_HostNameMismatch, QSslError::HostNameMismatch, 96},
    {sipName_InvalidCaCertificate, QSslError::InvalidCaCertificate, 96},
    {sipName_InvalidNotAfterField, QSslError::InvalidNotAfterField, 96},
    {sipName_InvalidNotBeforeField, QSslError::InvalidNotBeforeField, 96},
    {sipName_InvalidPurpose, QSslError::InvalidPurpose, 96},
    {sipName_NoError, QSslError::NoError, 96},
    {sipName_NoPeerCertificate, QSslError::NoPeerCertificate, 96},
    {sipName_NoSslSupport, QSslError::NoSslSupport, 96},
    {sipName_PathLengthExceeded, QSslError::PathLengthExceeded, 96},
    {sipName_SelfSignedCertificate, QSslError::SelfSignedCertificate, 96},
    {sipName_SelfSignedCertificateInChain, QSslError::SelfSignedCertificateInChain, 96},
    {sipName_SubjectIssuerMismatch, QSslError::SubjectIssuerMismatch, 96},
    {sipName_UnableToDecodeIssuerPublicKey, QSslError::UnableToDecodeIssuerPublicKey, 96},
    {sipName_UnableToDecryptCertificateSignature, QSslError::UnableToDecryptCertificateSignature, 96},
    {sipName_UnableToGetIssuerCertificate, QSslError::UnableToGetIssuerCertificate, 96},
    {sipName_UnableToGetLocalIssuerCertificate, QSslError::UnableToGetLocalIssuerCertificate, 96},
    {sipName_UnableToVerifyFirstCertificate, QSslError::UnableToVerifyFirstCertificate, 96},
    {sipName_UnspecifiedError, QSslError::UnspecifiedError, 96},
};

PyDoc_STRVAR(doc_QSslError, "\1QSslError()\n"
    "QSslError(QSslError.SslError)\n"
    "QSslError(QSslError.SslError, QSslCertificate)\n"
    "QSslError(QSslError)");


pyqt4ClassTypeDef sipTypeDef_QtNetwork_QSslError = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_CLASS,
        sipNameNr_QSslError,
        {0}
    },
    {
        sipNameNr_QSslError,
        {0, 0, 1},
        3, methods_QSslError,
        26, enummembers_QSslError,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    doc_QSslError,
    sipNameNr_PyQt4_QtCore_pyqtWrapperType,
    sipNameNr_sip_simplewrapper,
    0,
    slots_QSslError,
    init_type_QSslError,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QSslError,
    assign_QSslError,
    array_QSslError,
    copy_QSslError,
    release_QSslError,
    cast_QSslError,
    0,
    0,
    0,
    0,
    0,
    0
},
    0,
    0,
    0
};
