/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.15.5 on Thu Jan 31 12:54:41 2019
 *
 * Copyright (c) 2014 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt.
 * 
 * This file may be used under the terms of the GNU General Public
 * License versions 2.0 or 3.0 as published by the Free Software
 * Foundation and appearing in the files LICENSE.GPL2 and LICENSE.GPL3
 * included in the packaging of this file.  Alternatively you may (at
 * your option) use any later version of the GNU General Public
 * License if such license has been publicly approved by Riverbank
 * Computing Limited (or its successors, if any) and the KDE Free Qt
 * Foundation. In addition, as a special exception, Riverbank gives you
 * certain additional rights. These rights are described in the Riverbank
 * GPL Exception version 1.1, which can be found in the file
 * GPL_EXCEPTION.txt in this package.
 * 
 * If you are unsure which license is appropriate for your use, please
 * contact the sales department at sales@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtNetwork.h"

#line 40 "/home/cct/LabRAD/PyQt-x11-gpl-4.10.4/sip/QtNetwork/qssl.sip"
#include <qssl.h>
#line 34 "/home/cct/LabRAD/PyQt-x11-gpl-4.10.4/QtNetwork/sipQtNetworkQSsl.cpp"


static sipEnumMemberDef enummembers_QSsl[] = {
    {sipName_AnyProtocol, QSsl::AnyProtocol, 90},
    {sipName_Der, QSsl::Der, 85},
    {sipName_DnsEntry, QSsl::DnsEntry, 84},
    {sipName_Dsa, QSsl::Dsa, 86},
    {sipName_EmailEntry, QSsl::EmailEntry, 84},
    {sipName_Pem, QSsl::Pem, 85},
    {sipName_PrivateKey, QSsl::PrivateKey, 87},
    {sipName_PublicKey, QSsl::PublicKey, 87},
    {sipName_Rsa, QSsl::Rsa, 86},
    {sipName_SecureProtocols, QSsl::SecureProtocols, 90},
    {sipName_SslOptionDisableCompression, QSsl::SslOptionDisableCompression, 88},
    {sipName_SslOptionDisableEmptyFragments, QSsl::SslOptionDisableEmptyFragments, 88},
    {sipName_SslOptionDisableLegacyRenegotiation, QSsl::SslOptionDisableLegacyRenegotiation, 88},
    {sipName_SslOptionDisableServerNameIndication, QSsl::SslOptionDisableServerNameIndication, 88},
    {sipName_SslOptionDisableSessionTickets, QSsl::SslOptionDisableSessionTickets, 88},
    {sipName_SslV2, QSsl::SslV2, 90},
    {sipName_SslV3, QSsl::SslV3, 90},
    {sipName_TlsV1, QSsl::TlsV1, 90},
    {sipName_TlsV1SslV3, QSsl::TlsV1SslV3, 90},
    {sipName_UnknownProtocol, QSsl::UnknownProtocol, 90},
};


pyqt4ClassTypeDef sipTypeDef_QtNetwork_QSsl = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_NAMESPACE,
        sipNameNr_QSsl,
        {0}
    },
    {
        sipNameNr_QSsl,
        {0, 0, 1},
        0, 0,
        20, enummembers_QSsl,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    0,
    -1,
    -1,
    0,
    0,
    0,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0
},
    0,
    0,
    0
};
